# Nom de notre workflow
name: "Build and deploy Github pages"

# Événements sur lesquels il doit être déclenché
on:
  push:         # <- Déclenché lorsque l'on pousse du code...
    branches:
      - master  # <- ... mais seulement sur la branche "master"

jobs:

  # Notre job
  build-and-deploy:
    runs-on: ubuntu-latest

    # Tâches à effectuer, comme expliquées ci-dessus
    steps:

      # 1. On récupère le contenu du dépôt

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 2. Partie spécifique à Sphinx (installation des
      #    dépendances et génération de la doc)

      - name: "Set up node"
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: "Install"
        run: npm install

      - name: "Install"
        run: npm build


      # 3. Déploiement sur les Github Pages

      - name: "Deploy Github Pages"
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}